### ISSUE TITLE
Localhost test doesn't support multi-word messages

### ISSUE THREAD

**Issue by Chris-W-Weir** [smurthas/nch#1]
In terminal A, I run:
`./nch 1337 11337 localhost`
and in terminal B, I run:
`./nch 11337 1337 localhost`
and I get the attached output
<img width="571" alt="terminal a" src="https://cloud.githubusercontent.com/assets/5016626/23536458/de8f98f6-ff79-11e6-8fb1-12e304ce62a9.png">
<img width="589" alt="terminal b" src="https://cloud.githubusercontent.com/assets/5016626/23536459/de9006d8-ff79-11e6-8f0d-75e2b3db1e35.png">

**Comment by smurthas** [comment]
Ah yeah, shoot that's the `echo $3` portion of the send message function. It should probably have two `shift`s before it and then `echo $@`.
